const AUTH_ERROR = 401;
const CONFLICT_ERROR = 409;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const VALIDATION_ERROR = 400;
const DEFAULT_ERROR = 500;

module.exports = {
  AUTH_ERROR,
  CONFLICT_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND_ERROR,
  VALIDATION_ERROR,
  DEFAULT_ERROR,
};
